#!/bin/bash 
#SBATCH -J CALC_SYSTEM    
#SBATCH -o vasp.%j.out     
#SBATCH -e vasp.%j.err 
#SBATCH -N NODE         
#SBATCH -n CORE
#SBATCH -p vm-small      
#SBATCH -t TIME        
#SBATCH -A PHY24018

module load vasp/6.3.0
ibrun vasp_std > CALC.out
